---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: no
configure_osx: no
username: tonya

pass_repo: git@github.com:iTechyTony/password-store.git
pass_repo_accept_hostkey: yes
pass_repo_local_destination: ~/Repo/Personal/2Areas/password-store

dotfiles_repo: https://github.com/iTechyTony/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Repo/Personal/2Areas/dotfiles
dotfiles_files:
  - .config/alacritty
  - .config/fish
  - .config/picom
  - .config/polybar
  - .config/rofi
  - .config/surfraw
  - .config/systemd
  - .config/zathura
  - .emacs.d
  - .gitconfig
  - .gitignore_global
  - .offlineimaprc
  - .php-cs-fixer
  - .Xresources
  - .profile


# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages:
  - name: laravel/installer
    state: present
  - name: laravel/lumen-installer
    state: present
  - name: phpunit/phpunit
    state: present
  - name: phing/phing
    state: present
  - name: phpmd/phpmd
    state: present
  - name: squizlabs/php_codesniffer
    state: present
  - name: phpstan/phpstan
    state: present
  - name: psy/psysh
    state: present
  - name: laravel/envoy
    state: present
  - name: friendsofphp/php-cs-fixer
    state: present
  - name: cpriego/valet-linux
    state: present


gem_packages: []
  # - name: bundle
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: bower
    state: present
  - name: gulp
    state: present
  - name: grunt
    state: present
  - name: tern
    state: present
  - name: js-beautify
    state: present
  - name: ember-cli
    state: present
  - name: stylelint
    state: present
  - name: intelephense
    state: present
  - name: bash-language-server
    state: present
  - name: vscode-css-languageserver-bin
    state: present
  - name: dockerfile-language-server-nodejs
    state: present
  - name: vscode-html-languageserver-bin
    state: present
  - name: typescript-language-server
    state: present
  - name: vue-language-server
    state: present
pip_packages:
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
  - name: font-line
    state: present
  - name: mitogen
    state: present

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
