---
- hosts: all
  connection: local
  become: true
  vars_files:
    - default.config.yml
  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']
  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: kewlfft.aur
    - role: itechytony.php
      tags: ['php']
  tasks:
    - include: tasks/configure-user.yaml
      tags: ['configure-user']
    - include: tasks/arch/fonts.yaml
      tags: ['fonts']
    - include: tasks/arch/emacs.yaml
      tags: ['emacs']
    - include: tasks/arch/dev-tools.yaml
      tags: ['dev-tools']
    - include: tasks/arch/terminal.yaml
      tags: ['terminal']
    - include: tasks/arch/window-manager.yaml
      tags: ['window-manager']
    - include: tasks/arch/general.yaml
      tags: ['general']
    - include: tasks/arch/chats.yaml
      tags: ['chats']
    - include: tasks/arch/browser.yaml
      tags: ['browser']
    - include: tasks/arch/printer.yaml
      tags: ['printer']
    - include: tasks/arch/docker.yaml
      tags: ['docker']
    - include: tasks/arch/database.yaml
      tags: ['database']
    - include: tasks/arch/restclient.yaml
      tags: ['restclient']
    - include: tasks/extra-packages.yml
      tags: ['extra-packages']
