- name: Install surfraw
  package:
    name: surfraw
    state: present

- name: Install qutebrowser
  package:
    name: qutebrowser
    state: present

- name: Install firefox
  package:
    name: firefox
    state: present

- name: Install google chrome
  aur:
    use: yay
    name: google-chrome
  become: yes
  become_user: "{{username}}"

- name: Install browserpass-chrome
  aur:
    use: yay
    name: browserpass-chrome
  become: yes
  become_user: "{{username}}"

- name: Install brave browser
  package:
    name: brave
    state: present
